spring:
  # h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  # flyway
  flyway:
    enabled: true # Flywayを有効化
    baseline-on-migrate: true #　すでに存在するデータベスでもマイグレーションを有効にする
  # jpa
  jpa:
    show-sql: true